import type { Metadata } from "next";
import { Geist, Geist_Mono,Fira_Sans } from "next/font/google";
import {Provider} from "./components/ui/provider";
import { GlobalProvider } from "./context/GlobalProvider";
import {
Toaster
} from "./components/ui/toaster";

import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","900"], // Adjust as needed (e.g., "300", "500", "700")

});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Whatsapp clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${firaSans.variable}`} suppressHydrationWarning>
      <GlobalProvider>

       <Provider>
        <Toaster/>
        {children}
        </Provider> 
        </GlobalProvider>

      </body>
    </html>
  );
}
